/*
 * chi_main.c — Native Chi language compiler/runtime launcher
 *
 * Embeds LuaJIT with all runtime, stdlib, and compiler bytecode.
 * Three execution modes:
 *   1. Payload mode: runs bytecode appended to this binary (chi build output)
 *   2. Build mode:   'chi build FILE [-o OUT]' compiles and packages a Chi program
 *   3. Compiler mode: 'chi compile/run/FILE' — normal compiler CLI
 *
 * Payload format (appended to end of binary):
 *   [lua bytecode][size: 8 bytes LE uint64]["CHIEXE"]
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <limits.h>

#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"
#include "luajit.h"

/* Generated bytecode headers (from luajit -b) */
#include "gen/utf8_bc.h"
#include "gen/chistr_bc.h"
#include "gen/chi_runtime_bc.h"
#include "gen/std_chim_bc.h"
#include "gen/chicc_bc.h"
#include "gen/chi_build_bc.h"

#define CHI_VERSION "0.1.0"
#define PAYLOAD_MAGIC "CHIEXE"
#define PAYLOAD_MAGIC_LEN 6
#define PAYLOAD_TRAILER_LEN 14  /* 8 (size) + 6 (magic) */

/* ------------------------------------------------------------------ */
/*  Helpers                                                           */
/* ------------------------------------------------------------------ */

/* Get absolute path to this executable via /proc/self/exe */
static const char *get_exe_path(void) {
    static char path[PATH_MAX];
    ssize_t len = readlink("/proc/self/exe", path, sizeof(path) - 1);
    if (len <= 0) return NULL;
    path[len] = '\0';
    return path;
}

/*
 * Load pre-compiled bytecode into the Lua state and execute it.
 * Pushes one result onto the Lua stack (the chunk's return value, or nil).
 * Returns 0 on success, -1 on error (prints message to stderr).
 */
static int load_embedded(lua_State *L, const unsigned char *bc,
                         unsigned int size, const char *name) {
    if (luaL_loadbuffer(L, (const char *)bc, size, name) != 0) {
        fprintf(stderr, "Fatal: loading %s: %s\n", name,
                lua_tostring(L, -1));
        return -1;
    }
    if (lua_pcall(L, 0, 1, 0) != 0) {
        fprintf(stderr, "Fatal: running %s: %s\n", name,
                lua_tostring(L, -1));
        return -1;
    }
    return 0;  /* one result on stack */
}

/* Create the Lua 'arg' table from C argc/argv */
static void create_arg_table(lua_State *L, int argc, char **argv) {
    lua_createtable(L, argc > 1 ? argc - 1 : 0, 1);
    /* arg[0] = program name (Lua convention) */
    lua_pushstring(L, argv[0]);
    lua_rawseti(L, -2, 0);
    /* arg[1..N] = arguments */
    for (int i = 1; i < argc; i++) {
        lua_pushstring(L, argv[i]);
        lua_rawseti(L, -2, i);
    }
    lua_setglobal(L, "arg");
}

/* ------------------------------------------------------------------ */
/*  Runtime loading                                                   */
/* ------------------------------------------------------------------ */

/*
 * Load the Chi runtime stack (utf8, chistr, chi_runtime, stdlib).
 * After this call, the Lua state has all globals and package.loaded
 * entries needed to run any compiled Chi program.
 */
static int load_runtime(lua_State *L) {
    /* utf8 module — returns table, set as global */
    if (load_embedded(L, luaJIT_BC_utf8, luaJIT_BC_utf8_SIZE, "utf8") != 0)
        return -1;
    lua_setglobal(L, "utf8");

    /* chistr module — returns table, set as global */
    if (load_embedded(L, luaJIT_BC_chistr, luaJIT_BC_chistr_SIZE,
                      "chistr") != 0)
        return -1;
    lua_setglobal(L, "chistr");

    /* chi_runtime — sets globals: chi_new_string, chi_println, define(), etc. */
    if (load_embedded(L, luaJIT_BC_chi_runtime, luaJIT_BC_chi_runtime_SIZE,
                      "chi_runtime") != 0)
        return -1;
    lua_pop(L, 1);  /* discard nil return */

    /* stdlib — calls define() to populate package.loaded */
    if (load_embedded(L, luaJIT_BC_std_chim, luaJIT_BC_std_chim_SIZE,
                      "std.chim") != 0)
        return -1;
    lua_pop(L, 1);

    return 0;
}

/*
 * Load the chicc compiler on top of an already-loaded runtime.
 * Sets global arg=nil first so chicc's entry point doesn't fire.
 * After loading, overrides loadStdlib (stdlib already embedded) and
 * sets up chi_compile for eval()/compileLua() support.
 */
static int load_compiler(lua_State *L) {
    /* Ensure arg is nil so chicc's "if arg then cliMain(arg) end" doesn't fire */
    lua_pushnil(L);
    lua_setglobal(L, "arg");

    /* Load chicc — executes m1(), sets _CHICC + global exports */
    if (load_embedded(L, luaJIT_BC_chicc, luaJIT_BC_chicc_SIZE,
                      "chicc") != 0)
        return -1;
    lua_pop(L, 1);

    /* Override loadStdlib — stdlib is already loaded from embedded data */
    if (luaL_dostring(L,
            "_CHICC.loadStdlib = function() return true end\n"
            "loadStdlib = _CHICC.loadStdlib\n") != 0) {
        fprintf(stderr, "Fatal: overriding loadStdlib: %s\n",
                lua_tostring(L, -1));
        return -1;
    }

    /* Set chi_compile for eval()/compileLua() in Chi programs */
    if (luaL_dostring(L,
            "chi_compile = function(source)\n"
            "  local ns = newLuaCompilationEnv()\n"
            "  local result = compileToLua(source, ns)\n"
            "  if result and result.luaCode then return result.luaCode end\n"
            "  return nil\n"
            "end\n") != 0) {
        fprintf(stderr, "Fatal: setting chi_compile: %s\n",
                lua_tostring(L, -1));
        return -1;
    }

    return 0;
}

/* ------------------------------------------------------------------ */
/*  Payload detection and execution (for chi build output)            */
/* ------------------------------------------------------------------ */

/*
 * Check if this executable has a bytecode payload appended.
 * Reads last 14 bytes and checks for "CHIEXE" magic at offset 8.
 */
static int has_payload(const char *exe_path) {
    FILE *f = fopen(exe_path, "rb");
    if (!f) return 0;

    if (fseek(f, -PAYLOAD_TRAILER_LEN, SEEK_END) != 0) {
        fclose(f);
        return 0;
    }

    unsigned char trailer[PAYLOAD_TRAILER_LEN];
    if (fread(trailer, PAYLOAD_TRAILER_LEN, 1, f) != 1) {
        fclose(f);
        return 0;
    }
    fclose(f);

    return memcmp(trailer + 8, PAYLOAD_MAGIC, PAYLOAD_MAGIC_LEN) == 0;
}

/*
 * Read and execute the bytecode payload from the end of this executable.
 * Payload layout: [bytecode][size: 8 bytes LE][magic: "CHIEXE"]
 */
static int run_payload(lua_State *L, const char *exe_path) {
    FILE *f = fopen(exe_path, "rb");
    if (!f) {
        fprintf(stderr, "Error: cannot read %s\n", exe_path);
        return 1;
    }

    /* Read trailer */
    if (fseek(f, -PAYLOAD_TRAILER_LEN, SEEK_END) != 0) {
        fclose(f);
        fprintf(stderr, "Error: cannot seek in %s\n", exe_path);
        return 1;
    }

    unsigned char trailer[PAYLOAD_TRAILER_LEN];
    if (fread(trailer, PAYLOAD_TRAILER_LEN, 1, f) != 1) {
        fclose(f);
        fprintf(stderr, "Error: cannot read trailer from %s\n", exe_path);
        return 1;
    }

    /* Extract bytecode size (8-byte little-endian) */
    uint64_t bc_size = 0;
    for (int i = 7; i >= 0; i--)
        bc_size = (bc_size << 8) | trailer[i];

    /* Seek to bytecode start */
    if (fseek(f, -(long)(PAYLOAD_TRAILER_LEN + bc_size), SEEK_END) != 0) {
        fclose(f);
        fprintf(stderr, "Error: invalid payload size in %s\n", exe_path);
        return 1;
    }

    /* Read bytecode */
    char *bytecode = (char *)malloc((size_t)bc_size);
    if (!bytecode) {
        fclose(f);
        fprintf(stderr, "Error: out of memory (%lu bytes)\n",
                (unsigned long)bc_size);
        return 1;
    }

    if (fread(bytecode, (size_t)bc_size, 1, f) != 1) {
        fclose(f);
        free(bytecode);
        fprintf(stderr, "Error: failed to read payload\n");
        return 1;
    }
    fclose(f);

    /* Load and execute bytecode */
    int rc = luaL_loadbuffer(L, bytecode, (size_t)bc_size, "=payload");
    free(bytecode);

    if (rc != 0) {
        fprintf(stderr, "Error: %s\n", lua_tostring(L, -1));
        return 1;
    }

    rc = lua_pcall(L, 0, 0, 0);
    if (rc != 0) {
        fprintf(stderr, "Error: %s\n", lua_tostring(L, -1));
        return 1;
    }

    return 0;
}

/* ------------------------------------------------------------------ */
/*  Main                                                              */
/* ------------------------------------------------------------------ */

int main(int argc, char **argv) {
    const char *exe_path = get_exe_path();
    if (!exe_path) {
        fprintf(stderr, "Error: cannot determine executable path\n");
        return 1;
    }

    /* Handle --version early (before Lua init) */
    if (argc >= 2 && strcmp(argv[1], "--version") == 0) {
        printf("chi %s (native)\n", CHI_VERSION);
        return 0;
    }

    /* Create Lua state */
    lua_State *L = luaL_newstate();
    if (!L) {
        fprintf(stderr, "Error: failed to create Lua state\n");
        return 1;
    }
    luaL_openlibs(L);

    /* Load runtime (utf8, chistr, chi_runtime, stdlib) */
    if (load_runtime(L) != 0) {
        lua_close(L);
        return 1;
    }

    int exit_code = 0;

    if (has_payload(exe_path)) {
        /* ---- Payload mode ---- */
        /* This is a program built with 'chi build'. Execute the payload. */
        create_arg_table(L, argc, argv);
        exit_code = run_payload(L, exe_path);

    } else {
        /* ---- Compiler mode ---- */
        if (load_compiler(L) != 0) {
            lua_close(L);
            return 1;
        }

        if (argc >= 2 && strcmp(argv[1], "build") == 0) {
            /* Build command: chi build FILE [-o OUTPUT] */
            if (load_embedded(L, luaJIT_BC_chi_build,
                              luaJIT_BC_chi_build_SIZE, "chi_build") != 0) {
                lua_close(L);
                return 1;
            }
            lua_pop(L, 1);

            /* Set _CHI_EXE_PATH so chi_build.lua can copy this binary */
            lua_pushstring(L, exe_path);
            lua_setglobal(L, "_CHI_EXE_PATH");

            /* Call chi_build(arg) */
            create_arg_table(L, argc, argv);
            lua_getglobal(L, "chi_build");
            lua_getglobal(L, "arg");
            if (lua_pcall(L, 1, 1, 0) != 0) {
                fprintf(stderr, "Error: %s\n", lua_tostring(L, -1));
                exit_code = 1;
            } else {
                exit_code = (int)lua_tointeger(L, -1);
            }

        } else {
            /* Normal compiler mode: chi compile/run/FILE */
            create_arg_table(L, argc, argv);
            lua_getglobal(L, "cliMain");
            lua_getglobal(L, "arg");
            if (lua_pcall(L, 1, 1, 0) != 0) {
                fprintf(stderr, "Error: %s\n", lua_tostring(L, -1));
                exit_code = 1;
            } else {
                exit_code = (int)lua_tointeger(L, -1);
            }
        }
    }

    lua_close(L);
    return exit_code;
}
